FROM php:7-fpm-alpine
MAINTAINER Vladimir Pasechnik <vladimir.pasechnik@gmail.com>

ARG BUILD_DATE
ARG VCS_REF
ENV COMPOSER_ALLOW_SUPERUSER 1

LABEL Maintainer="Vladimir Pasechnik <vladimir.pasechnik@gmail.com>" \
      Description="Lightweight php 7.1 container based on alpine with xDebug enabled & composer installed." \
      org.label-schema.name="php-7-fpm-xdebug-alpine" \
      org.label-schema.description="Lightweight php 7.1 container based on alpine with xDebug enabled & composer installed." \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/linuxjuggler/php-7.1-xdebug-alpine.git" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0.0"

RUN apk update \
    && apk add  --no-cache git mysql-client curl openssh-client icu libpng libjpeg-turbo libmcrypt libmcrypt-dev \
    && apk add --no-cache --virtual build-dependencies icu-dev \
    libxml2-dev freetype-dev libpng-dev libjpeg-turbo-dev g++ make autoconf
RUN docker-php-source extract
RUN pecl install xdebug
RUN apk add geoip geoip-dev
RUN pecl install geoip-1.1.1
RUN docker-php-ext-enable xdebug
RUN pecl install mcrypt-1.0.1
RUN docker-php-ext-enable mcrypt
RUN docker-php-source delete
#RUN docker-php-ext-install mcrypt pdo_mysql intl zip xml
RUN docker-php-ext-install pdo_mysql
RUN echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN apk del build-dependencies
RUN apk del libmcrypt-dev
RUN rm -rf /tmp/*

# COPY php.ini /usr/local/etc/php/
COPY ./index.php /var/www

USER www-data

WORKDIR /var/www