version: "3"

# docker pull univerio/php5dev

services:
  php5dev:
    build:
      context: ../
      dockerfile: ./php5dev/Dockerfile
    image: univerio/phpdev:5-latest
    container_name: php5dev-image
    hostname: php5dev.univer.io
    ports:
      - 80:80
      - 443:443
